[package]
name = "imlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-tgiype = ["cdylib"]


[dependencies]
cxx = "1.0.94"

[build-dependencies]
cxx-build = "1.0.94"